### ISSUE TITLE
Idea on Indexing/Slicing of arrays

### ISSUE THREAD

**Issue by LuckyJosh** [pep-dortmund/toolbox-workshop#117]
I had an idea on how to make array indexing/slicing more visual and hopefully better to understand.
This is an [example for 1D](https://github.com/pep-dortmund/toolbox-workshop/files/1207781/array_index.pdf). 1D Indexing/Slicing is probably not very difficult to understand but I think in 2D this kind of visual representation could help.

**Comment by MaxNoe** [comment]
Looks good, we should include this graphic

**Comment by LuckyJosh** [comment]
Updated versions for 1D and 2D Arrays (either with or without code).
Maybe the 2D Versions should be split into two files, to be less big.
Where should I include those graphics, directly in the numpy notebook?

+ [Indexing1D.pdf](https://github.com/pep-dortmund/toolbox-workshop/files/1290828/Indexing1D.pdf)
+ [Indexing1D_code.pdf](https://github.com/pep-dortmund/toolbox-workshop/files/1290830/Indexing1D_code.pdf)
+ [Indexing2D.pdf](https://github.com/pep-dortmund/toolbox-workshop/files/1290829/Indexing2D.pdf)
+ [Indexing2D_code.pdf](https://github.com/pep-dortmund/toolbox-workshop/files/1290831/Indexing2D_code.pdf)

**Comment by MaxNoe** [comment]
Yes, if you convert it to svg, you can directly include them
