### ISSUE TITLE
Weighted Fits

### ISSUE THREAD

**Issue by drgh0st** [pep-dortmund/toolbox-workshop#119]
Whats about weighted fits for the AP? Should I make one example for weighted fits for the scipy part?
Or do you think its not necessary for the first year of Praktikum?

**Comment by MaxNoe** [comment]
Is there an experiment that needs weighted fits?

**Comment by drgh0st** [comment]
In the advanced praktikum its necessary, but i dont know an experiment in the beginner praktikum that need it really
