### ISSUE TITLE
Use Windows Subsystem For Linux?

### ISSUE THREAD

**Issue by MaxNoe** [pep-dortmund/toolbox-workshop#132]
I have tried it and everything works just fine.

I think we should switch windows 10 installation instructions to use the WSL.

Any opinions?

**Comment by VukanJ** [comment]
It seems to be much simpler than using ConEmu. I am for switching to WSL

**Comment by LuckyJosh** [comment]
One main caveats which will also loose importance over time:
Afaik, this is Win10 only
so we would require all Windows < 10 users to install a new OS in any case (either Win10 or Ubuntu) [on the other hand this might make the dual boot option more preferable]

Are we allowed to advertise the DreamSparks Program on the Installation site, if yes we should do this anyway.

**Comment by MaxNoe** [comment]
ConEmu is fine and I would still install it because it can directly start into the WSL and add the `Open WSL here` cotext menu. It's the msys2 bash thingy that makes problems.

I also would leave the Old instructions for people < Win 10. But XP and Vista are not supported by anything anymore and Windows 7 basically foces you to upgrade to 10.

**Comment by LuckyJosh** [comment]
Right, I meant msys2 not ConEmu :see_no_evil:

Also some people might need to be pushed slightly to change something for the better (either to an up-to-date windows or at least a dual boot system).  :smiley:

**Comment by VukanJ** [comment]
The two largest sources of confusion/Problems in the last two years were ConEmu(or msys2) and Windows. Eliminating one of them would be great.

**Comment by LuckyJosh** [comment]
I have a question for the installation instructions on this:
Generally, I am going to explain the installation of all software within the WSL,
like Anaconda, git, make, texlive, etc ... .

What should I do about atom?
Installation only within the WSL or  in both the WSL and Windows itself?

And should I add the instructions for Sumatra PDF on Windows 
or should I install evince or some other pdfreader within the WSL?

**Comment by MaxNoe** [comment]
I would install all GUIs on the windows side. The WSL can run windows executables!

**Comment by MaxNoe** [comment]
On a second thought: that might be problematic with plugins like `flake8`. mmh.

**Comment by MaxNoe** [comment]
https://hackernoon.com/wsl-hacks-making-atom-linters-work-with-windows-subsystem-for-linux-c86d42eaf09e

**Comment by LuckyJosh** [comment]
It would not be Windows if you would not have to jump through some hoops :sweat_smile: 

I guess thats the best solution right now,
if atom still doesnt work from within the WSL (as stated in the blog post).
 
But this seems to be to convoluted to expect
anyone of the participants to be able to understand this. 
 
Should we add another installation page(s) for the _next level_  stuff like linting?
I would wager that for most of the paticipants _How to do linting?_ is not their most important question, if at all.

**Comment by MaxNoe** [comment]
now on its way
