### ISSUE TITLE
VS Code binaries not open source

### ISSUE THREAD

**Issue by MaxNoe** [pep-dortmund/toolbox-workshop#149]
https://github.com/Microsoft/vscode/issues/17996

**Comment by phenomax** [comment]
-> https://github.com/VSCodium/vscodium als Drop-In Replacement ?

**Comment by MaxNoe** [comment]
Just noting: the arch package does not use the microsoft build, so `pacman -S code` is fine

**Comment by MaxNoe** [comment]
Done, right?

**Comment by phenomax** [comment]
What about other distros/OS
