### ISSUE TITLE
Editor

### ISSUE THREAD

**Issue by itoijala** [pep-dortmund/toolbox-workshop#15]
Es gab schon eine Diskussion über Editorempfehlungen.

Mir ist jetzt wieder eingfallen: git will häufiger mal einen Editor öffnen.
1. Welche Fälle gibt es (z.B. Commit-Message, Mergetool, git add -p, …)?
2. Was passiert dann auf Windows/Mac/Linux (ohne was eingestellt zu haben)?
3. Was sollten wir empfehlen?

In Git Bash (Windows) ist ein Minimal-Vim dabei, der dann geöffnet wird.

Es wird (zumindest auf Windows) häufig passieren, dass vim geöffnet wird.
Die Leute müssen da wenigstens raus können.

**Comment by MaxNoe** [comment]
Nach kurzem ausprobieren würde ich für alle Betriebssysteme Atom in die Anleitung schreiben.
https://atom.io/
Meinungen?

**Comment by itoijala** [comment]
Atom finde ich nicht so gut.
Wenn Leute auf Hacker News über Performance-Probleme und Abstürze klagen, will ich gar nicht wissen, wie es auf einem vier Jahre alten Netbook läuft……

Installiert es unter Windows eine Option im Kontextmenü, damit man beliebige Dateien damit öffnen kann (wie Notepad++)?

Wie soll es unter Linux installiert werden? Es befindet sich wohl nicht in den Repos der gängigen Distro-Versionen.

Für LaTeX-Highlighting müsste man noch ein Addon installieren…

Ich würde dabei bleiben, dass auf Windows Notepad++, auf Linux den vorhandenen und auf Mac irgendwas.
Auf Mac meinentwegen auch Atom.

Vielleicht wäre es nicht verkehrt, den Editorteil der Linksammlung auszubauen und ein oder zwei Sätze zu den verschiedenen Möglichkeiten zu schreiben.

**Comment by itoijala** [comment]
Wäre sowieso gut, die Linksammlung aufzuwerten und zu jedem Link einen Satz zu schreiben, worum es da geht.

**Comment by itoijala** [comment]
Wir haben uns wohl für Atom entschieden.

In der Link-Sammlung gibt es Links zu Alternativen.
