### ISSUE TITLE
Planning and advertising the Toolbox-Workshop 2019

### ISSUE THREAD

**Issue by LuckyJosh** [pep-dortmund/toolbox-workshop#174]
To be able to put up the posters in the (very) near future we should determine the 
timespan and location of the workshop. 

If possible I would suggest to use the same room as last year.

The semester starts on 07.10.2019  so the traditional "two-weeks-before" would be   
Toolbox: 23.09.2019 - 27.09.2019   
LaTeX: 30.09.2019 - 04.10.2019 (with the holiday being on thursday)

Is there any argument against these dates and the room?
If not we could fill out the necessary paperwork shortly. 
@MaxNoe, @chrbeckm  who of you wants to/should do that, I dont really know what you 
have to do with the forms once filled.

If the paperwork is done, and agreed upon we can update the poster and put it up as soon 
as possible.

**Comment by chrbeckm** [comment]
On my part there is no argument against the time and room. I won't be there on September 27th.
On Friday we could set up the forms together, so I know the procedure for the next years.

**Comment by LuckyJosh** [comment]
I cant be at uni tomorrow but maybe @MaxNoe has time to do that.
Either way, if you want to take a look at the forms, the blank one and the forms of the
last years can be found in the pep-nextcloud in the `Toolbox` folder.
