### ISSUE TITLE
polyglossia - french

### ISSUE THREAD

**Issue by chrbeckm** [pep-dortmund/toolbox-workshop#180]
Mit TExLIve 2019
kommt in _latex/content/text.tex_ Z.144 der Fehler
```
Module polyglossia Info: Language french already loaded; id is 16 on input line 23

warning  (node filter): error: ...19/texmf-dist/tex/latex/polyglossia/polyglossia-frpt.lua:180: attempt to call a nil value (upvalue 'remove_node')

.
\@orig\@centercr ...skip \else \@nolnerr \fi \par 
                                                  \@ifstar {\nobreak \@xcent...
l.23     \textfrench{ \enquote{foo}} \\
```
Bekannter issue 68 aus dem polyglossia repo

Lösungsvorschlag: andere Sprache mit ebenfalls interessanter `\enquote`-Weise suchen, oder rausnehmen

**Comment by MaxNoe** [comment]
> Lösungsvorschlag: andere Sprache mit ebenfalls interessanter \enquote-Weise suchen, oder rausnehmen

Verstehe ich das richtig: Französich ist einfach kaputt?

**Comment by MaxNoe** [comment]
Beobachtung 1):
Der Bug ist anscheinend in polyglossia gefixt und vermutlich bis zum Workshop auch in CTAN:
https://github.com/reutenauer/polyglossia/issues/222

Beobachtung 2):
Vielleicht sollten wir trotzdem auf babel wechseln:
https://tex.stackexchange.com/questions/482396/decide-between-polyglossia-and-babel-for-lualatex-in-2019/482401

**Comment by MaxNoe** [comment]
Ich werde mal versuchen auf babel zu wechseln
