### ISSUE TITLE
uncertainties - no lecture in the second week

### ISSUE THREAD

**Issue by chrbeckm** [pep-dortmund/toolbox-workshop#183]
There will be no lecture by Ms. Siegmann in the second week,
her parts will be in the second week of October.
Make sure you don't rely on those lectures in your presentations.

**Comment by stefangri** [comment]
Thanks for the info! I think we'll give a short introduction to uncertainty calculations like last year. But nothing more than the content at the beginning of the uncertainties notebook or what the students already know from Physik 1.
