### ISSUE TITLE
multiline sub-/superscript in sums, products, ...

### ISSUE THREAD

**Issue by cromeG** [pep-dortmund/toolbox-workshop#21]
Hallo zusammen,

ich habe gerade eine zweite Zeile in einem Subscript einer Summe benötigt.
Sowas (wenn auch nicht in Praktikumsprotokollen) kommt öfter mal vor, wenn man beispielsweise über i und j summiert und i \neq j.
Was haltet ihr davon, dies in die Folien einzubauen?

Auf die Schnelle schien mir die Lösung mit \substack (http://tex.stackexchange.com/questions/80460/expression-under-summation-on-multiple-lines) in Ordnung.

Was haltet ihr davon?

**Comment by kdungs** [comment]
Ich bin einer Meinung mit Igor was das betrifft. Der Kurs sollte sich wirklich auf Grundlagen konzentrieren.

Auf der andere Seite waere es vielleicht schoen eine Sammlung genau solcher Antworten zu haben. Wiki o.ae.

**Comment by cromeG** [comment]
Auch ich war von Anfang an der Meinung, dass das nicht zu den Grundlagen oder zu den Sachen gehört, die unbedingt in der Vorlesung erwähnt werden sollten!

Da allerdings bei den hinteren Folien auch advanced topics behandelt werden, für die sich ein Anfänger nicht unbedingt interessiert, dachte ich es sei einer Erwähnung wert.

**Comment by MaxNoe** [comment]
Googlen danach führt direkt auf entsprechende tex.stackexchange.com-Antworten. Deswegen müssen wir das denke ich nicht aufnehmen.

Vielleicht sollten wir eine Sammlung von guten Stackexchange Antworten machen?
