### ISSUE TITLE
LaTeX error in file input

### ISSUE THREAD

**Issue by chrbeckm** [pep-dortmund/toolbox-workshop#217]
The file input of plot.pdf in the template does not work anymore.
Error message is
```
LaTeX Warning: File `plot.pdf' not found on input line 6.

! error:  (file """plot".pdf) (pdf backend): cannot find image file '"""plot".pdf'
!  ==> Fatal error occurred, no output PDF file produced!=== TeX engine is 'LuaTeX'
Latexmk: Non-existent bbl file 'build/main.bbl'
 No file main.bbl.
Latexmk: Missing input file: 'plot.pdf' from line
  'LaTeX Warning: File `plot.pdf' not found on input line 6.'

```

In a test document it didn't work in any combination of `main.tex` and `plot.pdf` (in subdir, or the same one).

**Comment by MaxNoe** [comment]
This is a fuckup in the LaTeX kernel and grffile. For now the only solution is to not load grffile.

See https://github.com/ho-tex/oberdiek/issues/73.

As the LaTeX kernel itself now supports most stuff you needed grffile for, we should maybe just remove it and not look back.

The only thing that LaTeX itself cannot handle is filenames with multiple dots.
