### ISSUE TITLE
Perhaps don't update to TL2015?

### ISSUE THREAD

**Issue by itoijala** [pep-dortmund/toolbox-workshop#23]
See https://tex.stackexchange.com/questions/253512/luatex-wrong-missing-italic-correction-in-texlive-2015-vs-2014

**Comment by MaxNoe** [comment]
Or simply use xelatex instead. Or hope that this issue is fixed in three month.

**Comment by itoijala** [comment]
Or use the functioning workaround.
It's not like we have zero "hacks" at the moment…

**Comment by MaxNoe** [comment]
But I intend to have exactly zero hacks when the course starts again.

**Comment by itoijala** [comment]
Hacks are a fact of life.
Perhaps that's even a useful lesson for the course…

But seriously, that's not going to be easy, scrhack (for example) even has it in the name.

**Comment by itoijala** [comment]
Version 0.8 fixes the problems.
