### ISSUE TITLE
Explain what unicode is

### ISSUE THREAD

**Issue by maxnoe** [pep-dortmund/toolbox-workshop#239]
We often mention that something is good (or bad) because it does (not) support unicode.

People will probably not know what unicode is, so let's add a short intro to unicode and file encodings at the beginning of the workshop.

This basically boils down to "What is a textfile?"

**Comment by chrbeckm** [comment]
maybe after the intro slides about texteditors?
LF/CRLF too?

**Comment by maxnoe** [comment]
Or before, but yes, the intro seems appropriate.

Yes, including line endings might make sense to.
