### ISSUE TITLE
PDF Viewer

### ISSUE THREAD

**Issue by itoijala** [pep-dortmund/toolbox-workshop#24]
Do we want a list of usefull PDF viewers for Windows?
Mac and Linus should be fine but Acrobat on Windows locks the file which is especially bad for TeX use.

I think we should have a list of a few good ones and tell people to not use Acrobat Reader.

**Comment by MaxNoe** [comment]
Evince is fine on Windows.

**Comment by itoijala** [comment]
It seems to be abandoned. The Gtk+3 version does not exist for Windows and the Gtk+2 version probably has an extremely old version of poppler.

You wouldn't tell people to install Firefox version 20.

Here's a list:
- [evince](https://wiki.gnome.org/Apps/Evince/Downloads): ancient, potentially dangerous
- [okular](https://windows.kde.org/download.php): poppler, needs a couple of screenshots for installer
- [sumatra](http://www.sumatrapdfreader.org/free-pdf-reader.html): mupdf
- [mupdf](http://mupdf.com/): mupdf, no installer, just zip?

We will of course not recommend non-free software.

I would go with okular, but then again, I happen to like okular……

**Comment by itoijala** [comment]
I think we agree on Sumatra, discuss further in pep-dortmund/toolbox.pep-dortmund.de#14.
