### ISSUE TITLE
grffile isn't "currently broken" anymore

### ISSUE THREAD

**Issue by NicoWeio** [pep-dortmund/toolbox-workshop#253]
https://github.com/pep-dortmund/toolbox-workshop/blob/dd3dc85f7cbe767c3e9f6ae7052c6db99c06461d/exercises-latex/12-python/loesung-header.tex#L42-L44
https://github.com/pep-dortmund/toolbox-workshop/blob/dd3dc85f7cbe767c3e9f6ae7052c6db99c06461d/exercises-latex/08-figures/loesung.tex#L25-L27
https://github.com/pep-dortmund/toolbox-workshop/blob/44d3ba875f86506e820bf1087e87bee6cde206ed/latex-template/header.tex#L99-L102
https://github.com/pep-dortmund/toolbox-workshop/blob/51eef58b72feea56bf8971a24c5010c7b0c2a13b/latex/content/floats.tex#L31-L34

As discussed in Zoom.

**Comment by maxnoe** [comment]
Fixed in #254
