### ISSUE TITLE
Change matplotlib to the object-oriented approach

### ISSUE THREAD

**Issue by LuckyJosh** [pep-dortmund/toolbox-workshop#326]
An other change we discussed before was the change from
the `REPL`-style plotting with `plt. ...` to the use of 
`fig, ax = plt.subplots()`

**Comment by maxnoe** [comment]
I would be in favor of changing it. We should probably keep a small section in the end about "the old way" so people are aware when looking at the docs / stackoverflow

**Comment by LuckyJosh** [comment]
> Stefan and I did it for a workshop with PhD students, and they didn't complain, I liked it as a more scalable way. But then we need to change it everywhere, even exercises and notebooks you didn't think about beforehand...

At least it is easy to search for 😀
