### ISSUE TITLE
Teach to make Pull plots after fits to visually quantify goodness of fit

### ISSUE THREAD

**Issue by jpherdi** [pep-dortmund/toolbox-workshop#328]

**Comment by maxnoe** [comment]
What is a pull plot? I assume this is some CERN / LHC jargon...

Independent of what it is, I think this might be too specific for the toolbox workshop the lab courses to be included in the already quite full schedule

**Comment by jpherdi** [comment]
![image](https://user-images.githubusercontent.com/41512963/233464552-9fd304f4-bd89-4881-9469-ac98f7633c44.jpeg)

Something like this

**Comment by jpherdi** [comment]
![image](https://user-images.githubusercontent.com/41512963/233547171-0a757d1a-ceb9-4687-8468-c87213595e32.jpeg)

Something like this.
I would add this in the fitting chapter and it would take maybe one or two additional cells.

**Comment by chrbeckm** [comment]
Extending the remarks of Max: It might be too hard to understand, as well. Specifically with everything else in the two weeks.
We could think about a section on the website where we present stuff like this. As an outlook, based on the things we show.

**Comment by jpherdi** [comment]
alright. just an idea.

**Comment by LuckyJosh** [comment]
Sorry, didnt get to comment in time.
I think it would be a good idea in general to have some
'further reading' material e.g. a section in each notebook that we do not discuss in the workshop but is in the materals for interested/advanced paticipants as an easy next step.
