### ISSUE TITLE
Use a "template repository" for the template

### ISSUE THREAD

**Issue by maxnoe** [pep-dortmund/toolbox-workshop#341]
Instead of providing the template as a zip file for download, we could also use a "template repository".

This enables a "Start a new repository from this template" Button on github directly.

**Comment by maxnoe** [comment]
https://docs.github.com/en/repositories/creating-and-managing-repositories/creating-a-template-repository

**Comment by aknierim** [comment]
Good idea. This would also (hopefully) lead to more people reading the README...

**Comment by chrbeckm** [comment]
https://github.com/pep-dortmund/toolbox-workshop_protocol-template/tree/main

**Comment by jpherdi** [comment]
Can this be closed then?
