### ISSUE TITLE
64-bit and 32 bit bei ConEmu vertauscht?

### ISSUE THREAD

**Issue by MaxNoe** [pep-dortmund/toolbox-workshop#35]
x86 sollte 64 bit sein, oder?

**Comment by itoijala** [comment]
Bisschen mehr Info wäre nützlich……

**Comment by MaxNoe** [comment]
Ähm, ja. sorry. Wollte noch gar nicht posten.

**Comment by MaxNoe** [comment]
Bin auch dumm, alles richtig.
