### ISSUE TITLE
Scipy notebook

### ISSUE THREAD

**Issue by chrbeckm** [pep-dortmund/toolbox-workshop#363]
Change order of cells (scipy.constants)

**Comment by aknierim** [comment]
We should also make sure to explain the difference between the `constant`  methods (e.g. `const.h` or `const.Planck`) and the `constant.physical_constants` dictionary, i.e.
```python
import scipy.constants as const

planck = const.Planck  # returns the value
planck2 = const.physical_constants["Planck constant"]  # returns value, unit and uncertainty
```

Especially since both methods yield different returns (`value` vs. `(value, unit, uncertainty)`).

**Comment by aknierim** [comment]
Missing axis labels in linear regression plot
