### ISSUE TITLE
LaTeX: Mathe kürzen/umbauen

### ISSUE THREAD

**Issue by itoijala** [pep-dortmund/toolbox-workshop#37]
- Griechisch:
    - weg: `\wp`, Hebräisch, `\eth`
- Operatoren:
    - `\cdot`, `\times` vor `/`
    - `\eqcolon`
    - `\forall` (?)
- Indizes:
    - `\cramped` in advanced
- Funktionen:
    - `\mathclap` in advanced
- Große Operatoren:
    - `\sideset` weg
    - `\mathclap` in advanced
    - `\int^{} \int_0^{}` als Workaround für richtiges Spacing erwähnen (LuaTeX-Bug)
    - brauchen wir `\limits`?

**Comment by MaxNoe** [comment]
Finde ich alles gut.

`\limits`, nö. Eigentlich reicht das Standard-Verhalten, oder?
Ist auf jeden Fall nicht lebenswichtig.

**Comment by itoijala** [comment]
Sieht auch nicht besonders gut aus unter LuaTeX…

**Comment by MaxNoe** [comment]
Warum? Ich dachte der Bug mit der Italics-Correction wäre erledigt?

**Comment by itoijala** [comment]
`\limits` ist ein anderer Bug, womöglich im Font. Probier's dich einfach aus oder guck's dir in den Folien an (Folie 51).

`\int^{}` ist auch ein anderer Bug, der aber auch mit Italic-Correction zu tun hat. Den hat es auch wohl die ganze Zeit gegeben. Ist jedenfalls nicht gefixt, aber den Maintainern bekannt.

**Comment by MaxNoe** [comment]
Liegt nicht am Font, mit `TeX Gyre Pagella Math` taucht das gleiche Problem auf, wenn auch nicht so schlimm, weil das Integralzeichen in dem Font nicht so breit ist.
