### ISSUE TITLE
latex template is missing tabularray

### ISSUE THREAD

**Issue by LuckyJosh** [pep-dortmund/toolbox-workshop#406]
While working on my example lab report (coming soon :sweat_smile: ) I noticed that the header in
our latex template, does not have tabularray and still uses booktabs

https://github.com/pep-dortmund/toolbox-workshop/blob/e1e3029dd70e14a682bf70e877ba6dac9c7a4a0c/latex-template/header.tex#L102C1-L105C1

has to be changed to
```
\usepackage{tabularray}
\UseTblrLibrary{booktabs, siunitx}
```

Once I'm done with my lab report I'll update the template, but any one is welcome to fix it if you have time.

**Comment by LuckyJosh** [comment]
Oh, yeah ... I did not recall that we have a repo for the template :bulb:

**Comment by aknierim** [comment]
I guess we may want to remove the old template altogether then :D

**Comment by LuckyJosh** [comment]
I guess :+1:
