### ISSUE TITLE
Brauchen wir die Doku-Button?

### ISSUE THREAD

**Issue by MaxNoe** [pep-dortmund/toolbox-workshop#42]
Wir stellen texdoc vor.

**Comment by itoijala** [comment]
Ich finde sie ganz gut, um zu zeigen, dass es sich lohnt die Doku von diesem Paket anzugucken.
Jede Doku zu verlinken ist natürlich nicht sinnvoll.

Im Prinzip soll es für mich heißen, die Doku enthält noch weitere nützliche Sachen, die hier aber nicht vorgestellt werden.

Wir sollten also überprüfen, dass das bei allen Buttons der Fall ist.
