### ISSUE TITLE
Meeting 2015-10-01

### ISSUE THREAD

**Issue by bixel** [pep-dortmund/toolbox-workshop#52]
iPython Notebooks
- [x] Erster Fit: 1-Sigma Umgebung größer machen
- [x] Einfache Datentypen: Typen nacheinander vorstellen
- [x] Code und Kommentare Englisch!
- [x] None erwähnen
- [x] `in` umsortieren
- [x] `{{` erklären!
- [x] Explain `.T` for numpy
- [ ] Avoid using `,` when outputting several values

**Comment by ibab** [comment]
Explain `.T` for numpy
