### ISSUE TITLE
Werbung

### ISSUE THREAD

**Issue by ibab** [pep-dortmund/toolbox-workshop#53]
- [x] Fachschaftsverteiler
- [ ] Facebook
- [x] Praktikums-Vorkurs
- [x] Praktikums-Website

**Comment by itoijala** [comment]
Kann jemand bestätigen, dass die Mail erfolgreich rausgegangen ist?

**Comment by ccauet** [comment]
Ich hab sie über stud.physik@lists.tu-dortmund.de bekommen.

**Comment by itoijala** [comment]
Dann hat's geklappt.
