### ISSUE TITLE
Exercise Makefile fails

### ISSUE THREAD

**Issue by MaxNoe** [pep-dortmund/toolbox-workshop#55]
make fails in the exercises directory:

```
cp: target ‘build/exercises-latex-1’ is not a directory
Makefile:7: recipe for target 'all' failed
```

**Comment by itoijala** [comment]
Works for me.
Does it work after `make clean`?

**Comment by MaxNoe** [comment]
nope

**Comment by itoijala** [comment]
Is anything created in the `build` dir?

**Comment by MaxNoe** [comment]
Ah, on my Ubuntu there is a single folder `exercises-latex-{1,2,3}`

**Comment by itoijala** [comment]
I guess we need to set the `make` shell to `bash`.

**Comment by itoijala** [comment]
Probier's mal jetzt.

**Comment by MaxNoe** [comment]
Läuft
