### ISSUE TITLE
Für nächstes Jahr

### ISSUE THREAD

**Issue by itoijala** [pep-dortmund/toolbox-workshop#64]
- Vormittags vor erstem Termin betreutes Installieren
- Umfrage: Wie hat man vom Kurs erfahren

**Comment by DerKleineGauss** [comment]
Vorschlag: Ich denke irgendetwas (z.B. http://www.ctan.org/pkg/spelling ) in Richtung Rechtschreibprüfung wäre noch nice to have.

**Comment by kdungs** [comment]
Rechtschreibprüfung ist eher ein Editorproblem. Ist doch irgendwie eine frustrierende Vorstellung dass dein LaTeX-Dokument komplett kompiliert und in dem Sinne "fertig" ist und dann tauche da einige Wörter in rot auf. [GNU aspell](http://aspell.net/) beispielsweise integriert mit allen gängigen Editoren.

**Comment by MaxNoe** [comment]
This is awesome:

https://try.github.io/

**Comment by bixel** [comment]
Ich finde das hier sogar noch etwas besser, um die Funktion von git zu verstehen. http://pcottle.github.io/learnGitBranching/
