### ISSUE TITLE
Liste nützlicher Pakete

### ISSUE THREAD

**Issue by itoijala** [pep-dortmund/toolbox-workshop#68]
Mit kurzer Beschreibung

- todonotes
- tikz
- hepnames
- selnolig
- xparse
- IEEEtrantools
- tensor
- beamer

**Comment by MaxNoe** [comment]
Für mich:
* tikz 
* beamer
* xparse
zeigen, den rest nennen

**Comment by itoijala** [comment]
Ich glaube TikZ-Folien schaffen wir nicht mehr.

Die Python-Aufgabe wird viel Zeit fressen, die aber dort auch besser investiert ist, als bei TikZ.

Wir können, falls Zeit da ist, TikZ als Live-Demo einführen und dann zu Aufgaben übergehen.

**Comment by itoijala** [comment]
Willst du vielleicht noch eine Folie machen zu `latexmk -pvc`?

**Comment by MaxNoe** [comment]
Ich mach noch je eine Folie zu `latexmk -pvc` und `tikz`. Nur damit wir es auch erwähnt haben.

**Comment by itoijala** [comment]
Super!
