### ISSUE TITLE
header-matplotlib.tex not found on Ubuntu

### ISSUE THREAD

**Issue by MaxNoe** [pep-dortmund/toolbox-workshop#84]
On my Desktop (Xubuntu 15.04),  header-matplotlib.tex is not found when I run `python script/answers.py`

**Comment by itoijala** [comment]
Why dont't you use the Makefile?
You need to set `TEXINPUTS`.
Why `answers.py`?

**Comment by MaxNoe** [comment]
I'm using the Makefile, the error occures at `python script/answers.py`

**Comment by itoijala** [comment]
Please give me the exact output.
The Makefile looks ok.

**Comment by MaxNoe** [comment]
Ah, no. TEXINPUTS is missing for $(FIGURES)

**Comment by itoijala** [comment]
Ah, `answers.py` should ignore the matplotlibrc.
Adding an `mpl.rcdefaults()` should do it.

**Comment by MaxNoe** [comment]
Why should it ignore the settings? Looks good with it.

**Comment by itoijala** [comment]
Ok, that's the other solution.

**Comment by itoijala** [comment]
Then you could do that for the other one in intro as well.
Symlink the header and matplotlibrc.
