### ISSUE TITLE
Msys2 does not have windows PATH on win 10

### ISSUE THREAD

**Issue by MaxNoe** [pep-dortmund/toolbox-workshop#90]
I did a fresh install of mys2 on windows 10.

Msys2 does not overtake the system path. I had to set all path in the `.bashrc`.

Is there a better way?

**Comment by MaxNoe** [comment]
Ok, this was an update to msys:
https://sourceforge.net/p/msys2/discussion/general/thread/dbe17030/

Solution is to set an environment variable.

**Comment by texasbruce** [comment]
This should be by default turned on. What is the reasoning to keep it off?

**Comment by MaxNoe** [comment]
I don't know what the reasoning of the msys developers was.

Anyways, for the workshop we are encouriging the use of the WSL, so msys is not needed anymore.
