### ISSUE TITLE
Installationsanleitung updaten

### ISSUE THREAD

**Issue by MaxNoe** [pep-dortmund/toolbox-workshop#91]
* [ ] TeX Live 2016
* [ ] Msys2 auf Windows (`PATH`)
* [ ] Windows 10 als Standard?

**Comment by CarlArneThomann** [comment]
Problem mit dem pdf-Reader in Mac OS: Das Paket "microtype" sorgt für einen systemweiten Absturz in Vorschau/Preview, wenn man zu stark zoomt.

Empfehle anderen Reader: "Skim" (http://skim-app.sourceforge.net)
Außerdem praktisch: Reader springt nicht auf Seite 1, wenn Dokument neu gesetzt/geändert wurde.

**Comment by WortPixel** [comment]
Unter El Capitan 10.11.5 auf 2014er MacBook Pro mit Tex Live 2016 nicht reproduzierbar.

Kann ohne Probleme TeX Files mit `microtype` kompilieren, mit Preview öffnen und maximal heranzoomen.

**Comment by CarlArneThomann** [comment]
Sehr gut möglich, dass die Hardware daran beteiligt ist. MacBook Pro 2010, 4GB.
Das Verwenden von anderen pdf-Readern wie Adobe Acrobat oder Skim machen keine Probleme.
Auch das Weglassen von "microtype" schafft (vorerst) Abhilfe.

Dennoch könnte Skim empfohlen werden, weil es Dateiänderungen (etwa nach Neukompilieren) selbstständig anzeigt, ohne auf Seite 1 zu springen. Ist dies etwa nicht für Anfänger geeignet?

**Comment by bixel** [comment]
Ich hatte bisher auch noch keine Probleme mit "Vorschau" und bin eher dafür, dass man so wenig wie möglich und so viel wie nötig installiert. Wenn die Verwendung von Vorschau ein Showstopper ist, brauchen wir natürlich eine Alternative, ansonsten tendieren ich dazu das OS X-eigene Tool beizubehalten.

Falls wir vor Ort dieses Problem feststellen könnten wir immer noch den Workaround anbieten.

**Comment by MaxNoe** [comment]
Ich wäre auch dafür erstmal abzuwarten, ob sich das Problem auch bei anderen zeigt.

**Comment by MaxNoe** [comment]
@CarlArneThomann Hattest du das Problem vielleicht mit einem `pdftex` Dokument? Und nicht mit `lualatex`?

**Comment by CarlArneThomann** [comment]
@MaxNoe Nein, ich habe das Problem mit `lualatex` oder `latexmk --lualatex`. Im Netz finde ich dazu keine Lösung oder Beiträge mit ähnlichen Problemen. Der Ansatz von Phillip, dass meine Hardware nicht mehr zur Software passen könnte, geht vermutlich in die richtige Richtung. Der Rechner hat bei weitem nicht nur dieses (technische) Problem; es lohnt sich vermutlich nicht, dieses sinkende Schiff softwareseitig zu flicken. 

Mich störte in erster Linie an Vorschau, dass es bei `latexmk --pvc` nach jedem Kompilieren auf Seite 1 springt. Dies habe ich mit einem anderen Reader behoben, was zufällig zusätzlich das Zooming-Problem löste.
